export default function PrivacyPolicy() {
    const lastUpdatedDate = "March 29, 2025";
    
    return (
      <div className="max-w-4xl mx-auto p-6 text-gray-800">
        <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-sm text-gray-600 mb-4">Last Updated: {lastUpdatedDate}</p>
        
        <p className="mb-4">
          
Welcome to Rental Surat. Your privacy is important to us. This Privacy Policy outlines how we collect, use, and safeguard your information when you use our mobile application available on Android platforms.
</p>
        
        <h2 className="text-xl font-semibold mt-6">1. Interpretation and Definitions</h2>
        <h3 className="text-lg font-medium mt-4">Interpretation</h3>
        <p className="mb-4">Words with capitalized initials have defined meanings. These definitions apply regardless of whether they appear in singular or plural form.</p>
        
        <h3 className="text-lg font-medium mt-4">Definitions</h3>
        <ul className="list-disc pl-6 mb-4">
          <li><strong>Account:</strong> A unique account created for You to access our Service.</li>
          <li><strong>Company("We","Us"or"Our"):</strong> Rental Surat.</li>
          <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service:</strong> The mobile application provided by Rental Surat.</li>
          <li><strong>Service Provider:</strong> Any third-party entity that processes data on behalf of the Company.</li>
          <li><strong>Usage Data:</strong> Automatically collected data generated by Service usage.</li>
          <li><strong>You:</strong> The individual or entity using the Service.</li>
        </ul>
        
        <h2 className="text-xl font-semibold mt-6">2. Data Collection and Usage</h2>
        <h5>Personal Data</h5>
        <p className="mb-4">When using our Service, we may collect the following Personal Data:</p>
        <ul className="list-disc pl-6 mb-4">
          <li>Name</li>
          <li>Email address</li>
          <li>Phone number</li>
          <li>Address (including city, state, and postal code)</li>
          <li>Profile information for brokers and users</li>
        </ul>
        
        <p className="mb-4">We also collect Usage Data automatically, including:</p>
        <ul className="list-disc pl-6 mb-4">
          <li>Device information (e.g., mobile model, operating system)</li>
          <li>IP address</li>
          <li>App usage statistics</li>
          <li>Location data (if granted permission)</li>
        </ul>
        

        
        <h2 className="text-xl font-semibold mt-6">3. How We Use Your Data</h2>
        <p className="mb-4">We use your data for:</p>
        <ul className="list-disc pl-6 mb-4">
          <li>Providing and maintaining the Service</li>
          <li>Managing user and broker accounts</li>
          <li>Facilitating property listings and interactions</li>
          <li>Sending notifications, promotions, and updates</li>
          <li>Analyzing app performance and improving user experience</li>
          <li>Complying with legal requirements</li>
        </ul>
        
        <h2 className="text-xl font-semibold mt-6">4. Sharing and Disclosure of Data</h2>
        <p className="mb-4">We may share your data:</p>
        <ul className="list-disc pl-6 mb-4">
          <li>With other users (e.g., property listings and broker details)</li>
          <li>With Service Providers for analytics and support</li>
          <li>If required by law or for fraud prevention</li>
          <li>During business transfers (e.g., mergers, acquisitions)</li>
        </ul>
        
        <h2 className="text-xl font-semibold mt-6">5. Data Retention</h2>
        <p className="mb-4">We retain your data for as long as necessary to fulfill the purposes outlined in this Privacy Policy. You may request data deletion by contacting us.</p>
        
        <h2 className="text-xl font-semibold mt-6">6. Security of Your Data</h2>
        <p className="mb-4">We take reasonable security measures to protect your data. However, no digital transmission or storage system is 100% secure.</p>
        
        <h2 className="text-xl font-semibold mt-6">7. Your Rights</h2>
        <p>You have the right to:
        </p>
        <ul className="list-disc pl-6 mb-4">
          <li>Access, update, or delete your data</li>
          <li>Withdraw consent for certain data processing</li>
          <li>Opt out of promotional communications</li>
        </ul>
        
        <h2 className="text-xl font-semibold mt-6">8. Children's Privacy</h2>
        <p className="mb-4">Our Service is not intended for users under 13. We do not knowingly collect data from children.</p>
        
        <h2 className="text-xl font-semibold mt-6">9. Third-Party Links</h2>
        <p className="mb-4">Our app may contain links to third-party websites. We are not responsible for their privacy policies.</p>
        
        <h2 className="text-xl font-semibold mt-6">10. Changes to This Privacy Policy</h2>
        <p className="mb-4">We may update this policy periodically. We will notify users of changes via in-app notifications or email.</p>
        
        <h2 className="text-xl font-semibold mt-6">11. Contact Us</h2>
        <p className="mb-4">For privacy-related inquiries, contact us at:</p>
        <p className="font-medium">📧 Email: rentalsurat@gmail.com</p>
      </div>
    );
}
